AC_DEFUN([LLNL_FC_MAIN],
[AC_REQUIRE([LLNL_F90_LIBRARY_LDFLAGS])
AC_LANG_PUSH(Fortran)dnl
_AC_FC_MAIN
AC_LANG_POP(Fortran)dnl
])

AC_DEFUN([LLNL_F90_DUMMY_MAIN],
[AC_REQUIRE([LLNL_F90_LIBRARY_LDFLAGS])dnl
AC_LANG_PUSH(Fortran)dnl
_AC_FC_DUMMY_MAIN($@)
AC_LANG_POP(Fortran)dnl
])# LLNL_F90_DUMMY_MAIN

# LLNL_F90_WRAPPERS
# --------------
AC_DEFUN([LLNL_F90_WRAPPERS],
[AC_REQUIRE([LLNL_F90_NAME_MANGLING])dnl
AC_LANG_PUSH(Fortran)dnl
_AC_FC_WRAPPERS
AC_LANG_POP(Fortran)dnl
])# LLNL_F90_WRAPPERS
