#!/usr/bin/env python
# -*- python -*-
## @package sidl_token
#
# Data structure generated by the SIDL C/flex scanner.
#
# Please report bugs to <adrian@llnl.gov>.
#
# \authors <pre>
#
# Copyright (c) 2011, Lawrence Livermore National Security, LLC.
# Produced at the Lawrence Livermore National Laboratory
# Written by Adrian Prantl <adrian@llnl.gov>.
#  
# LLNL-CODE-473891.
# All rights reserved.
#  
# This file is part of BRAID. For details, see 
# http://compose-hpc.sourceforge.net/. 
# Please read the COPYRIGHT file for Our Notice and
# for the BSD License.
#
# </pre>
#
class Token:
    """\class Token
    This is the data structure generated by the C/flex scanner.
    """
    def __init__(self,ttype,value,lineno,lexpos):
        """
        Create a new token.
        """
        # print "token=",ttype,value,lineno,lexpos
        self.type = ttype
        self.value = value
        self.lineno = lineno
        self.lexpos = lexpos
    def __str__(self):
        return "LexToken(%s,%r,%d,%d)" % (self.type,self.value,self.lineno,self.lexpos)
    def __repr__(self):
        return str(self)
