#!/usr/bin/env python
# -*- python -*-
## @package token
#
# Data structure generated by the SIDL C/flex scanner.
#
# Please report bugs to <adrian@llnl.gov>.
#
# \authors
# Copyright (c) 2010, Lawrence Livermore National Security, LLC             \n 
# Produced at the Lawrence Livermore National Laboratory.                   \n 
# Written by the Components Team <components@llnl.gov>                      \n 
# UCRL-CODE-2002-054                                                        \n 
# All rights reserved.                                                      \n 
#                                                                           \n 
# This file is part of Babel. For more information, see                     \n 
# http://www.llnl.gov/CASC/components/. Please read the COPYRIGHT file      \n 
# for Our Notice and the LICENSE file for the GNU Lesser General Public     \n 
# License.                                                                  \n 
#                                                                           \n 
# This program is free software; you can redistribute it and/or modify it   \n 
# under the terms of the GNU Lesser General Public License (as published by \n 
# the Free Software Foundation) version 2.1 dated February 1999.            \n 
#                                                                           \n 
# This program is distributed in the hope that it will be useful, but       \n 
# WITHOUT ANY WARRANTY; without even the IMPLIED WARRANTY OF                \n 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the terms and    \n 
# conditions of the GNU Lesser General Public License for more details.     \n 
#                                                                           \n 
# You should have recieved a copy of the GNU Lesser General Public License  \n 
# along with this program; if not, write to the Free Software Foundation,   \n 
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA               \n 

class Token:
    """\class Token
    This is the data structure generated by the C/flex scanner.
    """
    def __init__(self,ttype,value,lineno,lexpos):
        """
        Create a new token.
        """
        # print "token=",ttype,value,lineno,lexpos
        self.type = ttype
        self.value = value
        self.lineno = lineno
        self.lexpos = lexpos
    def __str__(self):
        return "LexToken(%s,%r,%d,%d)" % (self.type,self.value,self.lineno,self.lexpos)
    def __repr__(self):
        return str(self)
